steps:
# Install necessary npm packages
- name: 'node:10'
  entrypoint: npm
  args: ["install"]
  dir: './client'
# Retrieve secrets
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args: ["-c", "for secret in $(gcloud secrets list --filter=\"labels.environment=${_ENV}\" --filter=\"labels.component=${_COMPONENT}\" --format=\"value(NAME)\"); do echo export $secret=\\\"$(gcloud secrets versions access --secret=$secret latest)\\\" >> build.env; done"]
  dir: './client'
# Generate static resources
- name: 'node:10'
  entrypoint: bash
  args: ["-c", "source build.env && npm run build"]
  dir: './client'
# Sync static content with the frontend bucket
- name: gcr.io/cloud-builders/gsutil
  args: ["-m", "rsync", "-r", "-c", "-d", "build", "${_BUCKET_URL}"]
  dir: './client'
