version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run install:server
            - persist_to_workspace:
                root: ./
                paths:
                  - node_modules
                  - server/node_modules
  test-code-quality:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ./
            - run: cd server && npm run test:types
            - run: cd server && npm run test:lint
  unit-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ./
            - run: cd server && npm run test:unit
workflows:
  build-and-test:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - master
                - qa
                - dev
      - test-code-quality:
          requires:
            - install
      - unit-test:
          requires:
            - install
