steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:$SHORT_SHA', './server']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy',
    '${_COMPONENT}-${_ENV}',
    '--project',
    '$PROJECT_ID',
    '--platform',
    'managed',
    '--region',
    '${_REGION}',
    '--image',
    '${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:$SHORT_SHA',
    '--memory',
    '1G',
    '--set-env-vars',
    '"ACCOUNT_SECURITY_API_KEY=sm://refugies-info/ACCOUNT_SECURITY_API_KEY"',
    '--set-env-vars',
    '"API_KEY=sm://refugies-info/API_KEY"',
    '--set-env-vars',
    '"API_SECRET=sm://refugies-info/API_SECRET"',
    '--set-env-vars',
    '"GCLOUD_CLIENT_EMAIL=sm://refugies-info/GCLOUD_CLIENT_EMAIL"',
    '--set-env-vars',
    '"GCLOUD_CLIENT_ID=sm://refugies-info/GCLOUD_CLIENT_ID"',
    '--set-env-vars',
    '"GCLOUD_CLIENT_X509=sm://refugies-info/GCLOUD_CLIENT_X509"',
    '--set-env-vars',
    '"GCLOUD_PKEY=sm://refugies-info/GCLOUD_PKEY"',
    '--set-env-vars',
    '"GCLOUD_PRIVATE_KEY_ID=sm://refugies-info/GCLOUD_PRIVATE_KEY_ID"',
    '--set-env-vars',
    '"MONGODB_PROD_URI=sm://refugies-info/MONGODB_PROD_URI"',
    '--set-env-vars',
    '"NODE_ENV=sm://refugies-info/NODE_ENV"',
    '--set-env-vars',
    '"OVH_PASS=sm://refugies-info/OVH_PASS"',
    '--set-env-vars',
    '"PORT=sm://refugies-info/PORT"',
    '--set-env-vars',
    '"PORTIO=sm://refugies-info/PORTIO"',
    '--set-env-vars',
    '"REACT_APP_ENV=sm://refugies-info/REACT_APP_ENV"',
    '--set-env-vars',
    '"REACT_APP_GOOGLE_ANALYTICS=sm://refugies-info/REACT_APP_GOOGLE_ANALYTICS"',
    '--set-env-vars',
    '"REACT_APP_GOOGLE_API_KEY=sm://refugies-info/REACT_APP_GOOGLE_API_KEY"',
    '--set-env-vars',
    '"REACT_APP_SITE_SECRET=sm://refugies-info/REACT_APP_SITE_SECRET"',
    '--set-env-vars',
    '"SECRET=sm://refugies-info/SECRET"',
    '--set-env-vars',
    '"TTS_KEY_1=sm://refugies-info/TTS_KEY_1"',
    '--set-env-vars',
    '"accountSid=sm://refugies-info/accountSid"',
    '--set-env-vars',
    '"airtableBase=sm://refugies-info/airtableBase"',
    '--set-env-vars',
    '"airtableApiKey=sm://refugies-info/airtableApiKey"',
    '--set-env-vars',
    '"authToken=sm://refugies-info/authToken"',
    '--service-account',
    '${_SA}',
    '--allow-unauthenticated']
